# Generated by Django 3.2.12 on 2022-06-21 10:17

from django.db import migrations, models
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=eshop.models.resolve_image_upload_path),
        ),
    ]
