# Generated by Django 3.2.12 on 2022-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catchphrase',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
